language: node_js
node_js:
  - 'stable'
install:
  - npm install -g codecov
before_script:
  - npm install
script:
  - npm run build
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)
